### ISSUE TITLE
Crash in emulator when isdebug=false

### ISSUE THREAD

**Issue by mirontoli** [christerdk/Malmofestivalen-for-Android#4]
Here is the screnshot from logcat:
![screencap](http://grab.by/ddjU)

```
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.google.android.apps.analytics.GoogleAnalyticsTracker
    at dk.christer.malmofestivalen.analytics.GoogleAnalyticsWrapper.StartTracking(GoogleAnalyticsWrapper.java:29)
    at dk.christer.malmofestivalen.StartActivity.setupAnalytics(StartActivity.java:263)
    at dk.christer.malmofestivalen.StartActivity.onCreate(StartActivity.java:61)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
    at android.app.ActivityThread.access$2300(ActivityThread.java:125)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4627)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by christerdk** [comment]
I'll try to reproduce right away...

**Comment by christerdk** [comment]
Ok, I think we have one of those classic "works on my machine" cases :) I have no problem running with isdebug=false, which was actually also what originally prompted me to ask you to turn it off (i forgot myself). 

I'm wondering if you have all the *.jar files included in your java Build Path? (Project -> Properties -> Java Build Path -> Libraries)

Let me know if you have any luck - not that it is a big issue, that you cannot run with isdebug=false, but of course we'd like it to work 100%.

**Comment by mirontoli** [comment]
You are right! It was exactly this issue. I had added them to build path (in order to be able to compile). But it wasn't enough. After Project -> Clean now everything runs.
