### ISSUE TITLE
java.lang.NoClassDefFoundError org.apache.commons.io.FileUtils

### ISSUE THREAD

**Issue by mirontoli** [christerdk/Malmofestivalen-for-Android#8]
Hi, I reinstalled my computer and I get this strange error:

```
FATAL EXCEPTION: AsyncTask #1
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:200)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.NoClassDefFoundError: org.apache.commons.io.FileUtils
at dk.christer.malmofestivalen.services.DBFileService.PlaceDefaultDatabase(DBFileService.java:75)
at dk.christer.malmofestivalen.StartActivity$CopyStandardDBTask.doInBackground(StartActivity.java:421)
at dk.christer.malmofestivalen.StartActivity$CopyStandardDBTask.doInBackground(StartActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
```

I have added org.apache.commons.io.jar to build path.

**Comment by mirontoli** [comment]
Found this: http://android.foxykeep.com/dev/how-to-fix-the-classdefnotfounderror-with-adt-17

**Comment by mirontoli** [comment]
I solved it by putting all jars to "libs" directory...
